#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
download_data.py

Download daily OHLCV data for the stock universe selected in
`data/sp500_top80_universe.csv` without using yfinance.

Default output:
    data/raw_prices/all_daily_prices.csv
    data/raw_prices/download_log.csv
    data/raw_prices/download_metadata.json
    data/raw_prices/by_ticker/<ticker>.csv

Data source:
    Yahoo Finance chart endpoint requested directly with `requests`.
    The script requests adjusted close via includeAdjustedClose=true.

Example:
    python download_data.py \
        --universe-path data/sp500_top80_universe.csv \
        --start-date 2015-01-01 \
        --end-date 2024-12-31 \
        --output-dir data/raw_prices
"""

from __future__ import annotations

import argparse
import json
import os
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd
import requests


YAHOO_HOSTS = [
    "query1.finance.yahoo.com",
    "query2.finance.yahoo.com",
]

DEFAULT_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    ),
    "Accept": "application/json,text/plain,*/*",
    "Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
    "Connection": "keep-alive",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Download daily adjusted prices without yfinance."
    )
    parser.add_argument(
        "--universe-path",
        default="data/sp500_top80_universe.csv",
        help="Path to universe CSV generated by the stock-selection script.",
    )
    parser.add_argument(
        "--start-date",
        default="2015-01-01",
        help="Start date, inclusive, YYYY-MM-DD.",
    )
    parser.add_argument(
        "--end-date",
        default="2024-12-31",
        help="End date, inclusive, YYYY-MM-DD.",
    )
    parser.add_argument(
        "--output-dir",
        default="data/raw_prices",
        help="Directory for raw downloaded data.",
    )
    parser.add_argument(
        "--ticker-column",
        default="auto",
        choices=["auto", "YahooTicker", "Ticker"],
        help=(
            "Column used as ticker. `auto` prefers YahooTicker and falls back to Ticker. "
            "Ticker values such as BRK.B are converted to Yahoo style BRK-B."
        ),
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=5,
        help="Maximum retries per ticker."
    )
    parser.add_argument(
        "--sleep-sec",
        type=float,
        default=0.75,
        help="Sleep seconds between ticker requests. Increase this if you hit rate limits."
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=30,
        help="HTTP timeout in seconds."
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing per-ticker CSV files. Otherwise cached files are reused."
    )
    return parser.parse_args()


def validate_date(date_str: str) -> str:
    try:
        datetime.strptime(date_str, "%Y-%m-%d")
    except ValueError as exc:
        raise ValueError(f"Invalid date {date_str!r}. Expected YYYY-MM-DD.") from exc
    return date_str


def to_unix_time_utc(date_str: str) -> int:
    """Convert YYYY-MM-DD to Unix timestamp at 00:00:00 UTC."""
    dt = datetime.strptime(date_str, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    return int(dt.timestamp())


def normalize_to_yahoo_ticker(ticker: str) -> str:
    """
    Convert common S&P 500 class-share tickers to Yahoo format.

    Examples:
        BRK.B -> BRK-B
        BF.B  -> BF-B
        AAPL  -> AAPL
    """
    s = str(ticker).strip()
    if not s or s.lower() == "nan":
        return ""
    return s.replace(".", "-").upper()


def safe_filename(ticker: str) -> str:
    return ticker.replace("/", "_").replace("\\", "_").replace(".", "_").replace("-", "_")


def load_universe(universe_path: str, ticker_column: str = "auto") -> pd.DataFrame:
    universe = pd.read_csv(universe_path)

    if ticker_column == "auto":
        if "YahooTicker" in universe.columns:
            selected_col = "YahooTicker"
        elif "Ticker" in universe.columns:
            selected_col = "Ticker"
        else:
            raise ValueError("Universe CSV must contain either YahooTicker or Ticker column.")
    else:
        selected_col = ticker_column
        if selected_col not in universe.columns:
            raise ValueError(f"Universe CSV does not contain required column: {selected_col}")

    universe = universe.copy()
    universe["InputTickerColumn"] = selected_col
    universe["DownloadTicker"] = universe[selected_col].map(normalize_to_yahoo_ticker)

    if "Ticker" in universe.columns:
        universe["OriginalTicker"] = universe["Ticker"].astype(str)
    else:
        universe["OriginalTicker"] = universe["DownloadTicker"]

    universe = universe[universe["DownloadTicker"].astype(bool)].copy()
    universe = universe.drop_duplicates(subset=["DownloadTicker"]).reset_index(drop=True)
    return universe


def request_yahoo_chart(
    ticker: str,
    period1: int,
    period2: int,
    timeout: int,
    max_retries: int,
    sleep_sec: float,
) -> Tuple[Dict[str, Any], str]:
    """
    Request Yahoo chart JSON.

    Returns:
        (json_data, url_used)
    """
    params = {
        "period1": period1,
        "period2": period2,
        "interval": "1d",
        "events": "history",
        "includeAdjustedClose": "true",
    }

    last_error: Optional[BaseException] = None

    for attempt in range(1, max_retries + 1):
        for host in YAHOO_HOSTS:
            url = f"https://{host}/v8/finance/chart/{ticker}"
            try:
                response = requests.get(
                    url,
                    params=params,
                    headers=DEFAULT_HEADERS,
                    timeout=timeout,
                )

                # Yahoo sometimes returns a short text/html error body under rate limits.
                if response.status_code in {429, 502, 503, 504}:
                    raise RuntimeError(
                        f"HTTP {response.status_code}: possible temporary rate limit or gateway error"
                    )

                response.raise_for_status()

                try:
                    data = response.json()
                except ValueError as exc:
                    preview = response.text[:300].replace("\n", " ")
                    raise RuntimeError(f"Response is not JSON. Preview: {preview}") from exc

                chart = data.get("chart", {})
                if chart.get("error") is not None:
                    raise RuntimeError(f"Yahoo chart error: {chart.get('error')}")

                if not chart.get("result"):
                    raise RuntimeError("Yahoo chart returned no result.")

                return data, response.url

            except Exception as exc:  # noqa: BLE001
                last_error = exc

        print(f"[Retry {attempt}/{max_retries}] {ticker} failed: {last_error}")
        time.sleep(sleep_sec * attempt)

    raise RuntimeError(f"Failed to request Yahoo chart data for {ticker}: {last_error}")


def parse_chart_json(data: Dict[str, Any], ticker: str) -> pd.DataFrame:
    result = data["chart"]["result"][0]

    timestamps = result.get("timestamp")
    if not timestamps:
        raise RuntimeError(f"No timestamps returned for {ticker}.")

    indicators = result.get("indicators", {})
    quotes = indicators.get("quote", [])
    if not quotes:
        raise RuntimeError(f"No OHLCV quote data returned for {ticker}.")

    quote = quotes[0]
    adjclose_blocks = indicators.get("adjclose", [])
    adjclose = None
    if adjclose_blocks:
        adjclose = adjclose_blocks[0].get("adjclose")

    if adjclose is None:
        raise RuntimeError(
            f"Adjusted close is missing for {ticker}. The cleaning script requires AdjClose."
        )

    n = len(timestamps)

    def get_list(name: str) -> List[Any]:
        values = quote.get(name)
        if values is None:
            return [None] * n
        return values

    df = pd.DataFrame(
        {
            "Date": pd.to_datetime(timestamps, unit="s", utc=True).date,
            "Ticker": ticker,
            "Open": get_list("open"),
            "High": get_list("high"),
            "Low": get_list("low"),
            "Close": get_list("close"),
            "AdjClose": adjclose,
            "Volume": get_list("volume"),
        }
    )

    df["Date"] = pd.to_datetime(df["Date"])

    numeric_cols = ["Open", "High", "Low", "Close", "AdjClose", "Volume"]
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # Keep rows with a valid adjusted close. Raw OHLC fields may occasionally be missing.
    df = df.dropna(subset=["AdjClose"])
    df = df.drop_duplicates(subset=["Date", "Ticker"], keep="last")
    df = df.sort_values("Date").reset_index(drop=True)

    if df.empty:
        raise RuntimeError(f"Empty dataframe after parsing and cleaning for {ticker}.")

    return df


def download_one_ticker(
    ticker: str,
    period1: int,
    period2: int,
    timeout: int,
    max_retries: int,
    sleep_sec: float,
) -> Tuple[pd.DataFrame, str]:
    data, url_used = request_yahoo_chart(
        ticker=ticker,
        period1=period1,
        period2=period2,
        timeout=timeout,
        max_retries=max_retries,
        sleep_sec=sleep_sec,
    )
    df = parse_chart_json(data, ticker=ticker)
    return df, url_used


def main() -> None:
    args = parse_args()
    start_date = validate_date(args.start_date)
    end_date = validate_date(args.end_date)

    if pd.Timestamp(start_date) > pd.Timestamp(end_date):
        raise ValueError("start-date must be earlier than or equal to end-date.")

    # Yahoo period2 is effectively right-open; add one calendar day to include end_date.
    period1 = to_unix_time_utc(start_date)
    period2 = to_unix_time_utc(
        (datetime.strptime(end_date, "%Y-%m-%d") + timedelta(days=1)).strftime("%Y-%m-%d")
    )

    output_dir = Path(args.output_dir)
    by_ticker_dir = output_dir / "by_ticker"
    output_dir.mkdir(parents=True, exist_ok=True)
    by_ticker_dir.mkdir(parents=True, exist_ok=True)

    universe = load_universe(args.universe_path, args.ticker_column)
    tickers = universe["DownloadTicker"].tolist()

    print(f"准备下载 {len(tickers)} 只股票")
    print(f"时间区间：{start_date} 到 {end_date}")
    print(f"输出目录：{output_dir}")

    all_data: List[pd.DataFrame] = []
    logs: List[Dict[str, Any]] = []

    for idx, row in universe.iterrows():
        ticker = row["DownloadTicker"]
        original_ticker = row.get("OriginalTicker", ticker)
        print(f"\n[{idx + 1}/{len(universe)}] Downloading {ticker} ...")

        single_path = by_ticker_dir / f"{safe_filename(ticker)}.csv"

        try:
            if single_path.exists() and not args.overwrite:
                df = pd.read_csv(single_path)
                df["Date"] = pd.to_datetime(df["Date"])
                url_used = "cached_file"
                print(f"使用缓存文件：{single_path}")
            else:
                df, url_used = download_one_ticker(
                    ticker=ticker,
                    period1=period1,
                    period2=period2,
                    timeout=args.timeout,
                    max_retries=args.max_retries,
                    sleep_sec=args.sleep_sec,
                )
                df.to_csv(single_path, index=False, encoding="utf-8-sig")

            all_data.append(df)

            logs.append(
                {
                    "OriginalTicker": original_ticker,
                    "DownloadTicker": ticker,
                    "Status": "Success",
                    "Rows": int(len(df)),
                    "StartDateDownloaded": str(df["Date"].min().date()),
                    "EndDateDownloaded": str(df["Date"].max().date()),
                    "File": str(single_path),
                    "URL": url_used,
                    "Error": "",
                }
            )

            print(
                f"成功：{ticker}, rows={len(df)}, "
                f"{df['Date'].min().date()} 到 {df['Date'].max().date()}"
            )

        except Exception as exc:  # noqa: BLE001
            logs.append(
                {
                    "OriginalTicker": original_ticker,
                    "DownloadTicker": ticker,
                    "Status": "Failed",
                    "Rows": 0,
                    "StartDateDownloaded": "",
                    "EndDateDownloaded": "",
                    "File": "",
                    "URL": "",
                    "Error": str(exc),
                }
            )
            print(f"失败：{ticker}, error={exc}")

        time.sleep(args.sleep_sec)

    log_df = pd.DataFrame(logs)
    log_path = output_dir / "download_log.csv"
    log_df.to_csv(log_path, index=False, encoding="utf-8-sig")

    if all_data:
        combined = pd.concat(all_data, ignore_index=True)
        combined = combined.drop_duplicates(subset=["Date", "Ticker"], keep="last")
        combined = combined.sort_values(["Ticker", "Date"]).reset_index(drop=True)
        combined_path = output_dir / "all_daily_prices.csv"
        combined.to_csv(combined_path, index=False, encoding="utf-8-sig")
    else:
        combined_path = output_dir / "all_daily_prices.csv"

    metadata = {
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "start_date": start_date,
        "end_date": end_date,
        "universe_path": args.universe_path,
        "output_dir": str(output_dir),
        "requested_asset_count": int(len(universe)),
        "successful_asset_count": int((log_df["Status"] == "Success").sum()),
        "failed_asset_count": int((log_df["Status"] == "Failed").sum()),
        "source": "Yahoo Finance chart endpoint requested directly with requests; yfinance is not used.",
        "adjusted_price_field": "AdjClose",
        "combined_output_path": str(combined_path),
        "download_log_path": str(log_path),
    }
    metadata_path = output_dir / "download_metadata.json"
    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, ensure_ascii=False, indent=2)

    print("\n========== 下载完成 ==========")
    print(f"请求股票数：{len(universe)}")
    print(f"成功股票数：{metadata['successful_asset_count']}")
    print(f"失败股票数：{metadata['failed_asset_count']}")
    print(f"合并日线数据：{combined_path}")
    print(f"下载日志：{log_path}")
    print(f"下载元数据：{metadata_path}")


if __name__ == "__main__":
    main()
